name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "pouyan.rafieifard@gmail.com"
          git config --global user.name "pouyanrfard"
          git remote add space https://huggingface_hub:${HF_TOKEN}@huggingface.co/spaces/pouyanrafieifard/summarization-app
          git push space main --force
